---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kebabo-test-redis-deployment
  labels:
    app: kebabo-test-redis-deployment
    username: kebabo
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kebabo-test-redis-deployment
      username: kebabo
      env: test
  template:
    metadata:
      name: kebabo-test-redis-deployment
      labels:
        app: kebabo-test-redis-deployment
        username: kebabo
        env: test
    spec:
      containers:
        - name: redis
          imagePullPolicy: Always
          image: redis:7
          env:
          - name: FLASK_APP
            value: "gene_api.py"
          ports:
          - name: http
            containerPort: 6379
          volumeMounts:
          - name: kebabo-app-data
            mountPath: "/data"
      volumes:
      - name: kebabo-app-data
        persistentVolumeClaim:
          claimName: kebabo-app-data
