---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kebabo-test-flask-deployment
  labels:
    app: kebabo-test-flask-deployment
    username: kebabo
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kebabo-test-flask-deployment
      username: jacksont
      env: test
  template:
    metadata:
      name: kebabo-test-flask-deployment
      labels:
        app: kebabo-test-flask-deployment
        username: kebabo
        env: test
    spec:
      containers:
        - name: kebabo-test-flask-deployment
          imagePullPolicy: Always
          image: kobiekabo/gene_api:1.0-hw8
          env:
            - name: REDIS-IP
              value: kebabo-test-redis-service
          ports:
            - containerPort: 5000
