---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kebabo-test-flask-deployment
  labels:
    username: kebabo
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kebabo-test-flask
  template:
    metadata:
      labels:
        app: kebabo-test-flask
        username: kebabo
        env: test
    spec:
      containers:
        - name: flask
          image: kobiekabo/gene_api:1.0
          imagePullPolicy: Always
          env:
            - name: kebabo-test-redis-service
              value: kebabo-test-redis-service
          ports:
            - containerPort: 5000
