---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kebabo-test-redis-pvc
  labels:  
    username: kebabo
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
