---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: test-kebabo-deployment
   labels:
     app: kebabo-test-redis
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: kebabo-test-redis
   template:
     metadata:
       labels:
         app: kebabo-test-redis
     spec:
       containers:
         - name: kebabo-containers
           image: redis:7
           command:
           volumeMounts:
           - name: test-kebabo-redis
             mountPath: "/data"
       volumes:
       - name: kebabo-test
         persistentVolumeClaim:
           claimName: kebabo-test
