---
apiVersion: v1
kind: Service
metadata:
  name: kebabo-test-flask-service
  labels:
    username: kebabo
    env: test
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: kebabo-test-flask
    username: kebabo
    env: test
