---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kebabo-test-redis-deployment
  labels:
    app: kebabo-test-redis-deployment
    username: kebabo
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kebabo-test-redis-deployment
      username: kebabo
      env: test
  template:
    metadata:
      name: kebabo-test-redis-deployment
      labels:
        app: kebabo-test-redis-deployment
        username: kebabo
        env: test
    spec:
      containers:
        - name: kebabo-test-redis-deployment
          imagePullPolicy: Always
          image: redis:7
          volumeMounts:
          - name: kebabo-test-redis-pvc
            mountPath: "/data"
      volumes:
      - name: kebabo-test-redis-pvc
        persistentVolumeClaim:
          claimName: kebabo-test-redis-pvc
