apiVersion: v1
kind: Service
metadata:
  name: kebabo-test-redis-service
  labels:
    username: kebabo
    env: test
spec:
  type: ClusterIP
  selector:
    app: kebabo-test-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
